export const skills = {
  jsts: "Javascript / Typescript",
  react: "React",
  tw: "Tailwind CSS",
  java: "Java",
  reactNative: "React Native",
  next: "Next.js",
  node: "Node.js",
  sql: "SQL",
  nosql: "No-SQL",
  solidity: "Solidity (Basic)",
  python: "Python",
  vite: "Vite",
  figma: "Figma",
};
